### ISSUE TITLE
[Question] Integrated key directory

### ISSUE THREAD

**Issue by silverpill** [fedi-e2ee/public-key-directory-specification#46]
The [Architecture](https://github.com/fedi-e2ee/public-key-directory-specification/blob/main/Architecture.md) document describes a system where "Fediverse Servers" and "Public Key Directory" are distinct services. Why is that?

Does it mean that people who run single-user instances have to rely on 3rd party service if they want to encrypt their messages? Can a Fediverse Server act as a Key Directory service?

**Comment by soatok** [comment]
> The [Architecture](https://github.com/fedi-e2ee/public-key-directory-specification/blob/main/Architecture.md) document describes a system where "Fediverse Servers" and "Public Key Directory" are distinct services. Why is that?

Many-to-few, for efficiency.

The intent is to make it a separate component. It can be run alongside an instance, or it can be run independently of one. Additionally, clusters of instances can share a public key directory for their segment of the Fediverse network.

> Can a Fediverse Server act as a Key Directory service?

If you want to, yes. I wouldn't recommend it, but it's not forbidden.

**Comment by silverpill** [comment]
>Many-to-few, for efficiency.

Do you expect key directory to be a resource-intensive service? In decentralized networks efficiency is traded off for self-reliance, so integrated solution should be prioritized unless it has some serious disadvantages.

>Whether this is first party or third party is immaterial; they other person will still need to trust it, and it's necessarily easier to trust transparency logs that are independent of the instance operator.

The same principle applies to trust. A prominent 3rd party service is easier to trust, but this is not how the network operates.

What attacks this design is supposed to prevent? I've read the [Threat Model](https://github.com/fedi-e2ee/public-key-directory-specification/blob/main/Specification.md#threat-model) section, but I still don't quite understand why transparency log should be served from a separate server.

>It's important to understand that, if you don't want to use Key Transparency for encryption, you are not required to. You can pass your public key to your friends out-of-band and do your own thing without any of my designs.

Sure, I can do my own thing, but I would prefer to use the protocol everyone else is using.

**Comment by soatok** [comment]
> Do you expect key directory to be a resource-intensive service? In decentralized networks efficiency is traded off for self-reliance, so integrated solution should be prioritized unless it has some serious disadvantages.

We're following the principles that underpin [secure code delivery](https://defuse.ca/triangle-of-secure-code-delivery.htm). One of the corners of this triangle is called **Userbase Consistency Verification**.

If everyone runs their own Public Key Directory as *part of* their Fedi server software, you won't get this property. Instead, you'll have a lot of silos that can arbitrarily lie about their history. Since the goal of end-to-end encryption is mostly **protect users from instance administrators** (which are the entities that otherwise have access to plaintext), taking steps to ensure independent instance operators are held accountable and kept honest is a more important priority than maximizing independence.

> The same principle applies to trust. A prominent 3rd party service is easier to trust, but this is not how the network operates.

Correct. I expect there will be *some* fragmentation. I wouldn't want to host public keys for Truth Social users, since I don't federate with them _anyway_.

Maximizing fragmentation is a non-goal, and runs contrary to achieving an important security property that discourages sophisticated attacks.

> Sure, I can do my own thing, but I would prefer to use the protocol everyone else is using.

Let's be clear: There is no guarantee that everyone--let alone *anyone*--will use anything I design. My design has zero official standing with the W3C. I'm not asking the W3C for permission to design this as securely as possible, so I don't expect to be granted any standing, either.

But even if this does get widely adopted: The public key transparency mechanism I'm designing in this GitHub repository is not mandatory. You are 100% allowed to publish your public key out-of-band and have your friends manually add it in order to use the overall E2EE protocol.

**Comment by silverpill** [comment]
>If everyone runs their own Public Key Directory as part of their Fedi server software, you won't get this property. Instead, you'll have a lot of silos that can arbitrarily lie about their history.

I think that depends on implementation, for example if history is replicated to other servers it will be harder to lie about it.

>But even if this does get widely adopted: The public key transparency mechanism I'm designing in this GitHub repository is not mandatory. You are 100% allowed to publish your public key out-of-band and have your friends manually add it in order to use the overall E2EE protocol.

Good to know. If it will not be mandatory in your [E2EE](https://github.com/soatok/mastodon-e2ee-specification/tree/main/components/public-keys) proposal then there is no problem.

>Let's be clear: There is no guarantee that everyone--let alone anyone--will use anything I design. My design has zero official standing with the W3C. I'm not asking the W3C for permission to design this as securely as possible, so I don't expect to be granted any standing, either.

There are no alternatives at the moment. A workgroup at W3C only has a feature wishlist and nothing more (and in any case, W3C doesn't decide what becomes a standard in Fediverse).

So there is a good chance that your design will be used by someone. In particular, I might be interested in implementing your E2EE protocol - but only if it will satisfy my requirements (no mandatory 3rd party services is one of them).

**Comment by soatok** [comment]
OK. I created #47 to ensure this is captured by the Architecture and Specification in the relevant sections.

**Comment by silverpill** [comment]
Thanks. I'll close the issue then
