### ISSUE TITLE
BurnDown and aux data

### ISSUE THREAD

**Issue by cheddarcrisp** [fedi-e2ee/public-key-directory-specification#66]
The fact that a BurnDown also removes aux data bothers me.

- This gives an awful lot of power to the instance administrator.
- It creates friction when a user wants to reset their fedi encryption, but not their aux data. They have to choose which one they can't afford to lose more.

I think the issue is that everything hinges on the fediverse identity. It's used to bootstrap the whole chain. What if the bootstrapping was done differently? I'm a crypto lightweight so this could easily fall apart.

How about bootstrapping by having the user add a root signing key first? Any message after that can be signed by the root key or an intermediate key. BurnDown would be changed so that it only revokes the fedi key and anything that uses the fedi key as a signing key. The initial fedi key would also need to be signed by one of the user's other keys. This might be a way to mitigate some malicious administrator attacks too, if there's an out-of-band way to validate that the signing key belongs to the user.

**Comment by soatok** [comment]
> It creates friction when a user wants to reset their fedi encryption, but not their aux data. They have to choose which one they can't afford to lose more.

Let me speak practically: They can simply re-enroll their aux data. But the aftermath of a BurnDown is always a blank slate.

BurnDown is not meant to be a well-tread path, employed willy-nilly all day long by careless users with a laissez faire attitude towards key management. It's a last resort that should set off practically every alarm bell on the Internet when someone actually uses it.

(Separately, I intend to eventually setup an observatory service that monitors PKD instances for instances of BurnDown messages and treats them as security incidents that warrant a deep investigation.)

And for that reason, users can opt out of it entirely through [Fireproof](https://github.com/fedi-e2ee/public-key-directory-specification/blob/main/Specification.md#fireproof).

> This gives an awful lot of power to the instance administrator.

This is unavoidable. See [this section of the security considerations](https://github.com/fedi-e2ee/public-key-directory-specification/blob/main/Specification.md#minimal-trust-of-instance-operators). Pay special attention to the "Position Statement".

> How about bootstrapping by having the user add a root signing key first?

What happens when they use that key? In essence, once a user pushes an `AddKey`, that **becomes** their root signing key for all future operations. The only difference between my design, and what you propose, is that there is a way for a user to recover access if they lose that root signing key.

> This might be a way to mitigate some malicious administrator attacks too, if there's an out-of-band way to validate that the signing key belongs to the user.

Again, the BurnDown message is meant to be extremely rare. It is named so provocatively, as to inspire a mental image of this GIF: 

![image](https://github.com/user-attachments/assets/4d818cdb-f869-49b2-bbb3-305c52034885)
